runtime: go
env: flex

env_variables:
  POSTGRES_CONNECTION: "user=postgres password=password dbname=dbname host=/cloudsql/INSTANCE_CONNECTION_NAME"

beta_settings:
  cloud_sql_instances: "INSTANCE_CONNECTION_NAME"
